version: '3.8'
services:
    kiwi-symfony:
        container_name: kiwi-php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "7171:80"
        volumes:
            - ./app:/var/www/html
        depends_on:
            - kiwi-db
    kiwi-db:
        container_name: kiwi-db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: db-user
            MYSQL_PASSWORD: db-password
        ports:
            - "9906:3306"
